# Configuraci칩n b치sica para Jekyll
title: "Ecos del anden"
description: "Visibilizar el como los usuarios se tienen que adaptar ala infraestructura del metro y no al reves"
baseurl: "/Ecosdelanden"
url: "https://rhernandezgar-code.github.io"

# Configuraci칩n b치sica de Jekyll
markdown: kramdown
highlighter: rouge
